### ISSUE TITLE
cl-ana.tensor:tensor-map raises condition when used with vectors with the fill-pointer different than capacity

### ISSUE THREAD

**Issue by kat-co** [ghollisjr/cl-ana#28]
I am using `cl-ana.generic-math:/` with two vectors which have a `capacity` which is larger than their `fill-pointer`, i.e.: `(make-array 20700 :fill-pointer 0)`. When `type-of` is called [here](https://github.com/ghollisjr/cl-ana/blob/master/tensor/tensor.lisp#L261) to be passed along as `type`, it returns something like `(vector t 20700)`. Then, further in the call chain, `make-sequence` is called with a type restriction and a length that disagree with one another: `(make-sequence (vector t 20700) 20640 :initial-element 0.0d0))`. This raises the condition:

```
The length requested (20640) does not match the type restriction in (VECTOR
                                                                     T
                                                                     20700).
```

In my case, this arises because I'm increasing a vector's capacity in increments of 100 as I populate it. I can correct this by only monotonically incrementing the capacity, but that will be less performant.

**Comment by ghollisjr** [comment]
This is something that I hadn't anticipated in building the tensor library, and I could use some feedback in determining how to resolve this problem:

My first inclination is to define a function "tensor-type" which simplifies the type of the input sequences; e.g., (vector T 10) becomes just vector, so that a new sequence will be created without worrying about the type length constraints.  Since the tensor library functions always create new objects, I don't see a problem with that approach directly, but I do see a slight blemish in the sense that if you put two arrays with different capacities and fill-pointers then you will get back an array that doesn't have that property.

**Comment by ghollisjr** [comment]
Ah and I discovered something: I don't see a way to supply the fill-pointer argument to make-sequence.  I think the best way forward therefore is to simplify the type, as the model behind the tensor library is to define math operators for sequences, and the fill-pointer issue is specific to arrays.

**Comment by ghollisjr** [comment]
Added suggested fix

**Comment by kat-co** [comment]
This is working great, thank you!
