### ISSUE TITLE
local hdf5-cffi 

### ISSUE THREAD

**Issue by quicklisp** [ghollisjr/cl-ana#42]
I can't use cl-ana's version of hdf5-cffi - what's the current issue with upstream? Are you considering forking and maintaining it?

**Comment by ghollisjr** [comment]
At the moment, upstream's groveler file is asking for variables that no longer exist in the current HDF5 version.  It's an open issue that we're waiting to be resolved by the HDF5 maintainers here:

https://github.com/HDFGroup/hdf5-cffi/pull/73#issuecomment-783484622

This may be a version incompatibility issue between HDF5 v. 1.12 and previous versions ultimately.  I'd very much like to leave maintaining hdf5-cffi to someone else, so I just added the local version so that cl-ana would still be usable while we wait for the official patch.

Out of curiosity, is the groveler failing due to not finding a pkg-config file, or is it a different issue?  On my Arch Linux system I had to add a link to a configuration file to help pkg-config find things.

Are you able to load the official hdf5-cffi as it is currently?

**Comment by quicklisp** [comment]
I didn't realize you had renamed the main system - I was confused because
there are clashes with secondary systems (examples and tests).

I don't think I currently have trouble building hdf5-cffi, but I'll
double-check.

**Comment by ghollisjr** [comment]
Aha that makes sense; would it help for me to remove the other systems and just keep cl-ana.hdf-cffi?

**Comment by ghollisjr** [comment]
I went ahead and removed those systems as it didn't make sense to have them in any case.
